### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0   jft.predict

### ISSUE THREAD

**Issue by dutyhong** [vinhkhuc/JFastText#7]
hello  ,  when i use the predict function to predict my label ,  it except the java.lang.IndexOutOfBoundsException error  , how can i solve it ? thank you

**Comment by vinhkhuc** [comment]
Instead of calling predict(text), can you call predict(text, 1) and check its output? I guess the output would be an empty list.

If so, probably your training data doesn't have correct format. [Here](https://github.com/vinhkhuc/JFastText/blob/master/src/test/resources/data/labeled_data.txt) is an example of how it should look like.

**Comment by dutyhong** [comment]
thank you for your suggestion, my problem has been solved

**Comment by vinhkhuc** [comment]
No problem. Glad that it helps.
